org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration=
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$CborConfiguration=
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$CborConfiguration.ConditionalOnClass=tools.jackson.dataformat.cbor.CBORMapper
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$JsonProblemDetailsConfiguration=
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$JsonProblemDetailsConfiguration.ConditionalOnClass=org.springframework.http.ProblemDetail
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$XmlConfiguration=
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$XmlConfiguration$XmlProblemDetailsConfiguration=
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$XmlConfiguration$XmlProblemDetailsConfiguration.ConditionalOnClass=org.springframework.http.ProblemDetail
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration$XmlConfiguration.ConditionalOnClass=tools.jackson.dataformat.xml.XmlMapper
org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration.ConditionalOnClass=tools.jackson.databind.json.JsonMapper
org.springframework.boot.jackson.autoconfigure.JacksonTesterTestAutoConfiguration=
org.springframework.boot.jackson.autoconfigure.JacksonTesterTestAutoConfiguration.AutoConfigureAfter=org.springframework.boot.jackson.autoconfigure.JacksonAutoConfiguration
